{"assignees":[],"author":{"id":"MDQ6VXNlcjEwNjQ3MDgy","is_bot":false,"login":"mroeschke","name":"Matthew Roeschke"},"body":"**Describe the bug**\r\nIndex accessors wrongly in `dir` for Index subclasses in `cudf.pandas`.\r\n\r\nI think this is because the proxy Index subclasses objects have `bases=(Index,)` which has the accessors as additional attributes.\r\n\r\n**Steps/Code to reproduce bug**\r\n```python\r\nIn [1]: %load_ext cudf.pandas\r\n\r\nIn [2]: import pandas as pd\r\n\r\nIn [3]: \"str\" in dir(pd.RangeIndex(2))\r\nOut[3]: True\r\n```\r\n**Expected behavior**\r\n```python\r\nIn [1]: import pandas as pd\r\n\r\nIn [2]: \"str\" in dir(pd.RangeIndex(2))\r\nOut[2]: False\r\n```\r\n\r\n**Environment overview (please complete the following information)**\r\n - Environment location: Bare-metal\r\n - Method of cuDF install: from source\r\n\r\n**Environment details**\r\nPlease run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details\r\n\r\n**Additional context**\r\nAdd any other context about the problem here.\r\n","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps5sK-ov","author":{"login":"wence-"},"authorAssociation":"CONTRIBUTOR","body":"This is just for auto-completion, right? `pd.RangeIndex(2).str` is a property that exists and raises a \"custom\" `AttributeError` (since `RangeIndex` does inherit from `Index`).\r\n\r\nThis happens because although we devolve to the slow type for `dir`, to avoid copies, we cache `dir(slow_type)` rather than doing `dir(slow_instance)`, and `\"str\" in dir(pd.RangeIndex)` is _true_.","createdAt":"2023-11-16T16:38:00Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/14419#issuecomment-1814817327","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5sLJ5P","author":{"login":"mroeschke"},"authorAssociation":"CONTRIBUTOR","body":"> This is just for auto-completion, right?\r\n\r\nMostly yes (also because there's a pandas unit test that validate that accessors like `str` are not in `dir(index subclass)`)","createdAt":"2023-11-16T17:04:27Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/14419#issuecomment-1814863439","viewerDidAuthor":false}],"createdAt":"2023-11-15T21:58:07Z","id":"I_kwDOBWUGps528wVW","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"},{"id":"LA_kwDOBWUGps8AAAABlj4eYg","name":"cudf.pandas","description":"Issues specific to cudf.pandas","color":"984DFB"}],"milestone":{"number":35,"title":"Proxying - cudf.pandas","description":"","dueOn":null},"number":14419,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] Index accessors wrongly in `dir` for Index subclasses in `cudf.pandas`","updatedAt":"2024-05-16T05:09:13Z","url":"https://github.com/rapidsai/cudf/issues/14419"}
