{"assignees":[{"id":"MDQ6VXNlcjMxOTA0MDU=","login":"shwina","name":"Ashwin Srinath"}],"author":{"id":"MDQ6VXNlcjcwNjAzMjc0","is_bot":false,"login":"amanlai","name":"Manlai Amar"},"body":"If I create a DatetimeIndex object using `cudf.date_range()` by passing `start`, `end` and `freq` parameters:\r\n```python\r\ncudf.date_range('2020-01-01', '2020-01-05', freq='D')\r\n\r\nDatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04'], \r\n              dtype='datetime64[ns]', freq='D')\r\n```\r\nAs you can see, the result is an object with length 4. The same code in pandas results in an object with length 5:\r\n```python\r\npd.date_range('2020-01-01', '2020-01-05', freq='D')\r\n\r\nDatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04', '2020-01-05'],\r\n              dtype='datetime64[ns]', freq='D')\r\n```\r\n\r\nIs it possible to make it consistent with pandas' `date_range()` in that the result includes both ends? Because, `closed` parameter is nonfunctional at the moment, to make `cudf.date_range()` produce the same output as its pandas counterpart, we need to add 1 `freq` to `end`, which creates a whole lot of work: convert the string to datetime, convert freq to timedelta and add them to define a new end.\r\n\r\nAnyway, is it possible to make it clear in the documentation that this is different from its pandas counterpart?\r\n\r\n<sup>I didn't know how to tag this since it's not really a bug. It's just different from pandas API that results in a subtle bug _in my code_.</sup>","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps50yMBZ","author":{"login":"shwina"},"authorAssociation":"CONTRIBUTOR","body":"I think this is a legitimate bug. Thanks for reporting!","createdAt":"2024-02-22T12:05:32Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/15116#issuecomment-1959313497","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps51Q3nK","author":{"login":"wence-"},"authorAssociation":"CONTRIBUTOR","body":"Also https://github.com/rapidsai/cudf/issues/12133","createdAt":"2024-02-27T18:30:20Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/15116#issuecomment-1967356362","viewerDidAuthor":false}],"createdAt":"2024-02-22T04:35:02Z","id":"I_kwDOBWUGps6ACoLA","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":null,"number":15116,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] Unlike its pandas counterpart, `cudf.date_range` doesn't include the end if it's specified","updatedAt":"2024-02-27T18:30:21Z","url":"https://github.com/rapidsai/cudf/issues/15116"}
