{"assignees":[],"author":{"id":"MDQ6VXNlcjExMjY1Mw==","is_bot":false,"login":"mattf","name":"Matthew Farrellee"},"body":"**Describe the bug**\r\nlast example in https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.cut.html\r\n\r\n**Steps/Code to reproduce bug**\r\n```\r\nIn [1]: import cudf\r\n\r\nIn [2]: cudf.__version__\r\nOut[2]: '23.02.00'\r\n\r\nIn [3]: import numpy as np\r\n\r\nIn [4]: s = cudf.Series(np.array([2, 4, 6, 8, 10]), index=['a', 'b', 'c', 'd', 'e'])\r\n   ...: cudf.cut(s, 3)\r\nOut[4]: ---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)\r\n    700                 type_pprinters=self.type_printers,\r\n    701                 deferred_pprinters=self.deferred_printers)\r\n--> 702             printer.pretty(obj)\r\n    703             printer.flush()\r\n    704             return stream.getvalue()\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)\r\n    392                         if cls is not object \\\r\n    393                                 and callable(cls.__dict__.get('__repr__')):\r\n--> 394                             return _repr_pprint(obj, self, cycle)\r\n    395 \r\n    396             return _default_pprint(obj, self, cycle)\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)\r\n    698     \"\"\"A pprint that just redirects to the normal repr function.\"\"\"\r\n    699     # Find newlines and replace them with p.break_()\r\n--> 700     output = repr(obj)\r\n    701     lines = output.splitlines()\r\n    702     with p.group():\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py in __repr__(self)\r\n   1323                 )\r\n   1324             else:\r\n-> 1325                 pd_series = preprocess.to_pandas()\r\n   1326             output = pd_series.to_string(\r\n   1327                 name=self.name,\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/contextlib.py in inner(*args, **kwds)\r\n     73         def inner(*args, **kwds):\r\n     74             with self._recreate_cm():\r\n---> 75                 return func(*args, **kwds)\r\n     76         return inner\r\n     77 \r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py in to_pandas(self, index, nullable, **kwargs)\r\n   1900         if index is True:\r\n   1901             index = self.index.to_pandas()\r\n-> 1902         s = self._column.to_pandas(index=index, nullable=nullable)\r\n   1903         s.name = self.name\r\n   1904         return s\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/categorical.py in to_pandas(self, index, **kwargs)\r\n    913         else:\r\n    914             categories = col.categories.dropna(drop_nan=True).to_pandas()\r\n--> 915         data = pd.Categorical.from_codes(\r\n    916             codes, categories=categories, ordered=col.ordered\r\n    917         )\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/arrays/categorical.py in from_codes(cls, codes, categories, ordered, dtype)\r\n    685         Categories (2, object): ['a' < 'b']\r\n    686         \"\"\"\r\n--> 687         dtype = CategoricalDtype._from_values_or_dtype(\r\n    688             categories=categories, ordered=ordered, dtype=dtype\r\n    689         )\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py in _from_values_or_dtype(cls, values, categories, ordered, dtype)\r\n    297             # Note: This could potentially have categories=None and\r\n    298             # ordered=None.\r\n--> 299             dtype = CategoricalDtype(categories, ordered)\r\n    300 \r\n    301         return cast(CategoricalDtype, dtype)\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py in __init__(self, categories, ordered)\r\n    184 \r\n    185     def __init__(self, categories=None, ordered: Ordered = False) -> None:\r\n--> 186         self._finalize(categories, ordered, fastpath=False)\r\n    187 \r\n    188     @classmethod\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py in _finalize(self, categories, ordered, fastpath)\r\n    338 \r\n    339         if categories is not None:\r\n--> 340             categories = self.validate_categories(categories, fastpath=fastpath)\r\n    341 \r\n    342         self._categories = categories\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py in validate_categories(categories, fastpath)\r\n    534                 raise ValueError(\"Categorical categories cannot be null\")\r\n    535 \r\n--> 536             if not categories.is_unique:\r\n    537                 raise ValueError(\"Categorical categories must be unique\")\r\n    538 \r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/_libs/properties.pyx in pandas._libs.properties.CachedProperty.__get__()\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/indexes/base.py in is_unique(self)\r\n   2384         Return if the index has unique values.\r\n   2385         \"\"\"\r\n-> 2386         return self._engine.is_unique\r\n   2387 \r\n   2388     @final\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.is_unique.__get__()\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine._do_unique_check()\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine._ensure_mapping_populated()\r\n\r\npandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.map_locations()\r\n\r\nTypeError: unhashable type: 'dict'\r\n```","closed":false,"closedAt":null,"comments":[],"createdAt":"2023-02-16T15:38:22Z","id":"I_kwDOBWUGps5epbvl","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMDEzOTg3MzUy","name":"0 - Backlog","description":"In queue waiting for assignment","color":"d4c5f9"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":null,"number":12790,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] cudf.cut fails on example from documentation","updatedAt":"2023-06-05T19:02:02Z","url":"https://github.com/rapidsai/cudf/issues/12790"}
