{"assignees":[{"id":"MDQ6VXNlcjExMjY5ODE=","login":"wence-","name":"Lawrence Mitchell"}],"author":{"id":"MDQ6VXNlcjExMjY5ODE=","is_bot":false,"login":"wence-","name":"Lawrence Mitchell"},"body":"**Describe the bug**\r\n```python\r\nimport cudf\r\nimport pandas as pd\r\nf = pd.Series([1, 2, 3], index=pd.CategoricalIndex([0, 1, 2]))\r\nf.loc[pd.Categorical([1])] # => second row.\r\ncf = cudf.from_pandas(f)\r\ncf.loc[pd.Categorical([1])] # => KeyErrror\r\n```\r\n\r\nI think this is similar to #13013 in that length-one categoricals are treated as scalars in some cases.\r\n\r\n**Expected behavior**\r\n\r\nProbably this lookup should work.","closed":false,"closedAt":null,"comments":[],"createdAt":"2023-03-27T10:28:01Z","id":"I_kwDOBWUGps5h3IWd","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"},{"id":"MDU6TGFiZWwyNTQ2NTIxMDI0","name":"improvement","description":"Improvement / enhancement to an existing function","color":"bfd4f2"}],"milestone":{"number":5,"title":"Pandas API Alignment and Coverage","description":"","dueOn":null},"number":13014,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] loc indexing with length-1 Categorical not possible","updatedAt":"2023-05-02T10:54:11Z","url":"https://github.com/rapidsai/cudf/issues/13014"}
