{"assignees":[],"author":{"id":"MDQ6VXNlcjEyNzI1MTEx","is_bot":false,"login":"GregoryKimball","name":"Gregory Kimball"},"body":"**Describe the bug**\r\n`cudf.read_text` throws an exception when reading a host buffer, unlike the CSV, Parquet, ORC and JSON readers. Hopefully it is straightforward to enable `cudf.read_text` to read from host buffers. \r\n\r\n**Steps/Code to reproduce bug**\r\nHere is a small code snippet that shows the exception:\r\n```\r\nfrom io import BytesIO\r\nimport cudf\r\n\r\ndf = cudf.DataFrame({'a':['aaaa','bbbb']})\r\n\r\nbuf = BytesIO()\r\ndf.to_csv(buf, index=False)\r\ndf2 = cudf.read_csv(buf) # this is ok\r\nprint(df2)\r\n\r\nbuf = BytesIO()\r\ndf.to_csv(buf, index=False)\r\ndf2 = cudf.read_text(buf, delimiter='\\n') # this crashes\r\nprint(df2)\r\n```\r\n\r\n**Expected behavior**\r\nI expect that `read_text` would support host buffers correctly in the python layer. \"multibyte_split\" works fine with HOST_BUFFER data source in the libcudf benchmarks.\r\n\r\n**Environment overview (please complete the following information)**\r\nnightly docker image from 23.08, A100 DGX workstation\r\n","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps56ZeNS","author":{"login":"Pavanmahaveer7"},"authorAssociation":"NONE","body":"Hi Gregory, I tried using read_text for reading but coudl not possible, as bytesio reads both strutured and unstrurted data and for read_text it handles unstrutured data, before data passing the structure data we have has to convert into unstructure,  and it did not possible here.  we can alternatively tried changing to series from data frame , i tried like that, but we dont reuqire the function of read_text here.  is the issue with read_text here that it cannot handle the data from bytesio or something else","createdAt":"2024-04-13T05:23:03Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/13734#issuecomment-2053497682","viewerDidAuthor":false}],"createdAt":"2023-07-22T21:20:47Z","id":"I_kwDOBWUGps5sS627","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMDEzOTg3MzUy","name":"0 - Backlog","description":"In queue waiting for assignment","color":"d4c5f9"},{"id":"MDU6TGFiZWwxMDE2MzMyOTQ4","name":"good first issue","description":"Good for newcomers","color":"7057ff"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"},{"id":"MDU6TGFiZWwxMTg1MjQ0MTQy","name":"cuIO","description":"cuIO issue","color":"fef2c0"}],"milestone":null,"number":13734,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] `cudf.read_text` throws an exception when reading a host buffer","updatedAt":"2024-04-13T05:23:04Z","url":"https://github.com/rapidsai/cudf/issues/13734"}
