{"assignees":[],"author":{"id":"MDQ6VXNlcjExNjY0MjU5","is_bot":false,"login":"galipremsagar","name":"GALI PREM SAGAR"},"body":"**Describe the bug**\r\nInvestigate hangs in `tests/io/parser/common/test_read_errors.py` and enable running it in `cudf.pandas` tests.\r\n\r\nThis set of tests is being ignored here: https://github.com/rapidsai/cudf/blob/aab6137c80c50eccc5007120f7140cfe6646b5e0/python/cudf/cudf/pandas/scripts/run-pandas-tests.sh#L36C10-L36C52\r\n","closed":false,"closedAt":null,"comments":[],"createdAt":"2024-04-01T22:02:48Z","id":"I_kwDOBWUGps6ERZEr","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"},{"id":"LA_kwDOBWUGps8AAAABlj4eYg","name":"cudf.pandas","description":"Issues specific to cudf.pandas","color":"984DFB"}],"milestone":{"number":36,"title":"cudf.pandas API coverage","description":"","dueOn":null},"number":15432,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] Enable running `tests/io/parser/common/test_read_errors.py` in `cudf.pandas` tests","updatedAt":"2024-05-17T20:16:12Z","url":"https://github.com/rapidsai/cudf/issues/15432"}
