{"assignees":[{"id":"MDQ6VXNlcjMxOTA0MDU=","login":"shwina","name":"Ashwin Srinath"}],"author":{"id":"MDQ6VXNlcjgyNDY5NDk=","is_bot":false,"login":"honno","name":"Matthew Barber"},"body":"In the [interchange protocol](https://data-apis.org/dataframe-protocol/latest/API.html), `describe_categorical` should return a dict, but cuDF returns a tuple\r\n\r\n```python\r\n>>> df = cudf.DataFrame({\"foo\": cudf.Series([0, 1], dtype=\"category\")})\r\n>>> interchange_df = df.__dataframe__()\r\n>>> interchange_col = interchange_df.get_column_by_name(\"foo\")\r\n>>> interchange_col.describe_categorical\r\n(False, True, {0: 0, 1: 1})\r\n>>> type(interchange_col.describe_categorical)\r\ntuple  # should be dict\r\n```\r\n\r\nRelevant code returning a tuple as opposed to dict\r\n\r\nhttps://github.com/rapidsai/cudf/blob/edc5062bdcc3e12755603b0ad07a4d271fe95261/python/cudf/cudf/core/df_protocol.py#L295\r\n\r\nThis prevents interchanging dataframes with categorical columns, e.g. with pandas\r\n```python\r\n>>> from pandas.api.exchange import from_dataframe\r\n>>> from_dataframe(df)\r\n.../pandas/core/exchange/from_dataframe.py:184, in categorical_column_to_series(col)\r\n    169 \"\"\"\r\n    170 Convert a column holding categorical data to a pandas Series.\r\n    171 \r\n   (...)\r\n    180     that keeps the memory alive.\r\n    181 \"\"\"\r\n    182 categorical = col.describe_categorical\r\n--> 184 if not categorical[\"is_dictionary\"]:\r\n    185     raise NotImplementedError(\"Non-dictionary categoricals not supported yet\")\r\n    187 mapping = categorical[\"mapping\"]\r\nTypeError: tuple indices must be integers or slices, not str\r\n```\r\n\r\n\r\npandas and modin are compliant here, but interestingly vaex currently returns a tuple too https://github.com/vaexio/vaex/issues/2113","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps5JK6Vj","author":{"login":"github-actions"},"authorAssociation":"NONE","body":"This issue has been labeled `inactive-30d` due to no recent activity in the past 30 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed. This issue will be labeled `inactive-90d` if there is no activity in the next 60 days.","createdAt":"2022-08-25T18:03:10Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/11332#issuecomment-1227597155","viewerDidAuthor":false}],"createdAt":"2022-07-22T09:20:25Z","id":"I_kwDOBWUGps5OXXzC","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":{"number":5,"title":"Pandas API Alignment and Coverage","description":"","dueOn":null},"number":11332,"projectCards":[{"project":{"name":"v22.12 Release"},"column":{"name":"Issue-P1"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] Interchange `Column.describe_categorical` is a tuple, not a dict","updatedAt":"2023-04-02T22:40:25Z","url":"https://github.com/rapidsai/cudf/issues/11332"}
